Repository Handsol/nbc-final-kkuittoo, pull requests merged in 2025-04, with the labels that each got.

#6 Hotfix/#7-Team column 수정
  prisma/schema.prisma
Labels: 🐞 BugFix, 🐻 민경, 📬 API

#8 Feat/#2 - habits routes handler 엔드포인트 작성
  package.json
  pnpm-lock.yaml
  src/app/(main-contents)/layout.tsx
  src/app/api/habits/[id]/route.ts
  src/app/api/habits/route.ts
  src/app/api/user-points/route.ts
  src/types/mypage.type.ts
Labels: 🌱 수진, 📬 API

#9 Feat/#3-Team/TeamMember 관련 route handler 구현
  src/app/api/teams/[id]/member/route.ts
  src/app/api/teams/[id]/route.ts
  src/app/api/teams/route.ts
  src/types/teams.ts
Labels: ✨ Feature, 🐻 민경, 📬 API

#11 Feat/#4 - Google Social Login 구현
  src/app/api/auth/[...nextauth]/route.ts
  src/app/page.tsx
  src/components/login/GoogleLogin.tsx
  src/types/next-auth.d.ts
Labels: ✨ Feature, ♣ 한솔, 📬 API

#17 Bugfix/#16-Google login error 해결
  prisma/schema.prisma
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/habits/[id]/route.ts
  src/app/api/habits/route.ts
  src/app/api/teams/[id]/member/route.ts
  src/app/api/teams/[id]/route.ts
  src/app/api/teams/route.ts
  src/app/api/user-points/route.ts
  src/app/layout.tsx
  src/components/login/GoogleLogin.tsx
  src/constants/path.ts
  src/lib/providers/authProvider.tsx
Labels: 🐞 BugFix, 🐻 민경, 📬 API

#19 Bugfix/#18-Google login Status 수정
  next.config.mjs
  src/components/login/GoogleLogin.tsx
Labels: 🐞 BugFix, ♣ 한솔, 📬 API

#20 Feat/#15-User Route Handler 구현
  src/app/api/users/[id]/route.ts
  src/app/api/users/route.ts
  src/types/profile.type.ts
Labels: ✨ Feature, ♣ 한솔, 📬 API

#22 Feat/#12 my page UI
  src/app/(main-contents)/mypage/page.tsx
  src/app/api/habits/[id]/route.ts
  src/app/api/habits/route.ts
  src/app/api/user-points/route.ts
  src/components/mypage/AddHabitButton.tsx
  src/components/mypage/HabitItem.tsx
  src/components/mypage/HabitList.tsx
  src/components/mypage/MyPageCalendar.tsx
  src/components/mypage/MyPageHabits.tsx
  src/components/mypage/MyPageTeam.tsx
  src/constants/error-messages.constants.ts
  src/constants/habits.constants.ts
  src/lib/services/habit-actions.services.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Html&css, 🌱 수진

#23 Feat/#14 rank teams 페이지 구현
  src/app/(main-contents)/rank/teams/TeamRankContent.tsx
  src/app/(main-contents)/rank/teams/page.tsx
  src/app/(main-contents)/rank/teams/team-rank-content.tsx
  src/components/team/TeamRankCard.tsx
  src/lib/queries/useTeamQuery.ts
  src/lib/services/teamServices.ts
  src/types/teams.ts
Labels: ✨ Feature, 👾 본승

#28 Feat/#13-Team UI 구현 및 빌드오류 해결
  components.json
  package.json
  pnpm-lock.yaml
  src/_sample/app/clientPage.tsx
  src/_sample/app/serverPage.tsx
  src/_sample/components/SampleClientComponent.tsx
  src/_sample/constants/sample.ts
  src/_sample/lib/mutations/useSampleMutation.tsx
  src/_sample/lib/providers/sampleProvider.tsx
  src/_sample/lib/queries/useSampleQuery.tsx
  src/_sample/lib/server-actions/samle-server-action.ts
  src/_sample/lib/services/sampleServices.ts
  src/app/(main-contents)/team/[id]/page.tsx
  src/app/api/teams/[id]/member/route.ts
  src/app/api/teams/[id]/route.ts
  src/app/api/teams/route.ts
  src/app/globals.css
  src/components/team/TeamCalendar.tsx
  src/components/team/TeamInfo.tsx
  src/components/team/TeamMemberCard.tsx
  src/components/team/TeamMemberList.tsx
  src/components/team/TeamRankCard.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/progress.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/constants/path.ts
  src/hooks/use-toast.ts
  src/lib/queries/useTeamQuery.ts
  src/lib/services/team-actions.services.ts
  src/lib/services/team.services.ts
  src/lib/services/teamServices.ts
  src/lib/utils.ts
  src/types/teams.type.ts
  tailwind.config.ts
Labels: 🐞 BugFix, ✨ Feature, 🐻 민경

#31 Feat/#24 habit route handler refactor
  src/app/api/habits/[id]/route.ts
  src/app/api/habits/route.ts
  src/app/api/user-points/route.ts
  src/constants/error-messages.constants.ts
  src/constants/http-status.constants.ts
  src/lib/utils/auth-route-handler.utils.ts
  src/lib/utils/habit-route-handler.utils.ts
Labels: 🔨 Refactor, 🌱 수진

#33 Refactor/#29-Team관련 route handler 및 페이지 비즈니스 로직 refactor
  src/app/api/teams/[id]/member/route.ts
  src/app/api/teams/[id]/route.ts
  src/app/api/teams/member/[id]/route.ts
  src/app/api/teams/route.ts
  src/components/team/TeamMemberCard.tsx
  src/components/team/TeamMemberList.tsx
  src/constants/error-messages.constants.ts
  src/constants/http-status.constants.ts
  src/constants/validation.constants.ts
  src/lib/services/team-actions.services.ts
  src/lib/utils/auth-route-handler.utils.ts
  src/lib/utils/team-validation.utils.ts
Labels: ✨ Feature, 🔨 Refactor, 🐻 민경

#35 Feat/#34-Team페이지 UI 수정
  src/app/(main-contents)/layout.tsx
  src/app/(main-contents)/team/[id]/page.tsx
  src/components/team/TeamCalendar.tsx
  src/components/team/TeamChat.tsx
  src/components/team/TeamInfo.tsx
  src/components/team/TeamMemberCard.tsx
  src/components/team/TeamMemberList.tsx
  src/components/ui/progress.tsx
  src/lib/services/team-actions.services.ts
Labels: 🎨 Html&css, 🐻 민경

#41 Feat/#36-teamBio 수정 로직 구현
  package.json
  pnpm-lock.yaml
  src/app/api/teams/[id]/route.ts
  src/components/team/TeamBio.tsx
  src/components/team/TeamInfo.tsx
  src/constants/error-messages.constants.ts
  src/lib/mutations/useTeamBioMutation.ts
  src/lib/providers/TQProvider.tsx
  src/lib/queries/useSingleTeamQuery.ts
  src/lib/queries/useTeamQuery.ts
  src/lib/services/team-client.services.ts
  src/lib/services/team.services.ts
  src/lib/utils/team-validation.utils.ts
Labels: ✨ Feature, 🐻 민경, 📬 API

#42 Feat/#32 mypage UI + 유저 포인트 추가 로직
  public/images/test01.png
  src/app/(main-contents)/layout.tsx
  src/app/(main-contents)/mypage/page.tsx
  src/app/api/habits/[id]/route.ts
  src/app/api/habits/route.ts
  src/app/api/user-points/route.ts
  src/components/common/CommonInputBar.tsx
  src/components/mypage/AddHabitButton.tsx
  src/components/mypage/HabitItem.tsx
  src/components/mypage/HabitList.tsx
  src/components/mypage/MyPageCalendar.tsx
  src/components/mypage/MyPageHabits.tsx
  src/components/mypage/MyPageProfile.tsx
  src/components/mypage/MyPageTeam.tsx
  src/components/mypage/MyTeam.tsx
  src/components/mypage/NoTeam.tsx
  src/components/mypage/habits/HabitContent.tsx
  src/components/mypage/habits/HabitForm.tsx
  src/components/mypage/habits/HabitItem.tsx
  src/components/mypage/habits/HabitList.tsx
  src/components/mypage/habits/habit-form/HabitFormRepeatDays.tsx
  src/components/mypage/habits/habit-form/HabitFormTags.tsx
  src/constants/habits.constants.ts
  src/lib/hooks/useHabitForm.ts
  src/lib/mutations/useAddPointMutation.ts
  src/lib/queries/useHabitsQuery.ts
  src/lib/services/habit-actions.services.ts
  src/lib/services/user-points.services.ts
  src/lib/utils/habit-validation.utils.ts
  src/lib/utils/habit.utils.ts
  src/types/mypage.type.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Html&css, 🌱 수진

#43 Refactor/#30-User 관련 Route Handler 리팩토링
  src/app/api/users/[id]/route.ts
  src/app/api/users/route.ts
  src/app/layout.tsx
  src/components/login/GoogleLogin.tsx
  src/components/login/LoginButton.tsx
  src/components/login/LogoutButton.tsx
  src/constants/error-messages.constants.ts
  src/constants/validation.constants.ts
  src/lib/utils/auth.ts
  src/lib/utils/team-validation.utils.ts
  src/lib/utils/user-response.utils.ts
  src/lib/utils/user-validation.utils.ts
  src/types/profile.type.ts
Labels: ✨ Feature, 🔨 Refactor, ♣ 한솔, 📬 API

#47 Feat/#21-Layout 기본 구현
  public/images/logo_test.png
  public/images/user_lv1.png
  src/app/api/users/[id]/route.ts
  src/app/layout.tsx
  src/components/layout/LayoutWrapper.tsx
  src/components/layout/MainLayout.tsx
  src/components/layout/NavButton.tsx
  src/components/layout/Sidebar.tsx
  src/components/login/GoogleLogin.tsx
Labels: ✨ Feature, 🎨 Html&css, ♣ 한솔

#53 Feat/#52-공통 컴포넌트(LinkButton, Title) 구현
  src/components/common/Title.tsx
  src/components/common/button/LinkButton.tsx
  src/constants/mode.constants.ts
Labels: ✨ Feature, 🎨 Html&css, 🐻 민경

#50 Feat/#27 유저 랭킹 페이지 기능 구현
  src/app/(main-contents)/layout.tsx
  src/app/(main-contents)/rank/teams/TeamRankContent.tsx
  src/app/(main-contents)/rank/teams/page.tsx
  src/app/(main-contents)/rank/teams/team-rank-content.tsx
  src/app/(main-contents)/rank/users/page.tsx
  src/app/(main-contents)/rank/users/userRankContent.tsx
  src/app/api/teams/route.ts
  src/components/rank/TeamRankCard.tsx
  src/components/rank/UserRankCard.tsx
  src/components/team/TeamRankCard.tsx
  src/constants/query-keys.constants.ts
  src/lib/queries/useTeamQuery.ts
  src/lib/queries/useUserQuery.ts
  src/lib/services/team-client.services.ts
  src/lib/services/team.client.services.ts
  src/lib/services/user-client.services.ts
  src/types/rank-users.type.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Html&css, 👾 본승, 📬 API

#56 Feat/#55-Common Components(Text, User Title) 구현
  src/components/common/Text.tsx
  src/components/common/Title.tsx
  src/components/common/UserTitle.tsx
  src/components/common/button/LinkButton.tsx
  src/constants/mode.constants.ts
Labels: ✨ Feature, ♣ 한솔

#60 Feat/#49-팀 생성 기능 구현
  public/images/emblem-cat.png
  public/images/emblem-deer.png
  public/images/emblem-lion.png
  public/images/emblem-owl.png
  public/images/user_lv2.png
  public/images/user_lv3.png
  public/images/user_lv4.png
  public/images/user_lv5.png
  src/app/(main-contents)/@modal/(.)make-team/page.tsx
  src/app/(main-contents)/@modal/default.tsx
  src/app/(main-contents)/layout.tsx
  src/app/(main-contents)/make-team/page.tsx
  src/app/(main-contents)/rank/users/page.tsx
  src/app/(main-contents)/team/[id]/page.tsx
  src/app/api/teams/route.ts
  src/components/common/Title.tsx
  src/components/common/button/LinkButton.tsx
  src/components/layout/Sidebar.tsx
  src/components/login/LoginButton.tsx
  src/components/login/LogoutButton.tsx
  src/components/mypage/MyPageTeam.tsx
  src/components/mypage/MyTeam.tsx
  src/components/mypage/NoTeam.tsx
  src/components/team/TeamForm.tsx
  src/components/team/team-create/TeamEmblemSelector.tsx
  src/components/team/team-create/TeamInputs.tsx
  src/components/team/team-create/TeamOpenToggle.tsx
  src/components/team/team-create/TeamSizeSelector.tsx
  src/constants/error-messages.constants.ts
  src/constants/path.constants.ts
  src/constants/path.ts
  src/constants/placeholder.constants.ts
  src/constants/teams.constants.ts
  src/lib/hooks/useTeamCreateContents.ts
  src/lib/hooks/useTeamCreateForm.ts
  src/lib/mutations/useTeamBioMutation.ts
  src/lib/mutations/useTeamOpenMutation.ts
  src/lib/services/team-actions.services.ts
  src/lib/services/team-client.services.ts
  src/lib/services/team.client.services.ts
  src/lib/utils/auth.ts
  src/lib/utils/modal.utils.ts
Labels: ✨ Feature, 🎨 Html&css, 🐻 민경, 📬 API

#57 Refactor/#51 habit refactoring 및 유효성 검사
  package.json
  pnpm-lock.yaml
  src/components/mypage/habits/HabitForm.tsx
  src/components/mypage/habits/HabitItem.tsx
  src/components/mypage/habits/habit-form/HabitFormInput.tsx
  src/lib/hooks/useHabitForm.ts
  src/lib/mutations/useAddPointMutation.ts
  src/lib/mutations/useHabitMutation.ts
  src/lib/mutations/useOptimisticMutation.ts
  src/lib/schema/habit-form.schema.ts
  src/lib/utils/habit-validation.utils.ts
  src/lib/utils/habit.utils.ts
  src/types/mypage.type.ts
Labels: ✨ Feature, 🔨 Refactor, 🌱 수진

#59 Feat/#54-모달 공통 컴포넌트 구현
  src/app/(main-contents)/rank/teams/TeamDetailModalContents.tsx
  src/app/(main-contents)/rank/teams/TeamRankContent.tsx
  src/components/common/commonModal.tsx
  src/components/rank/TeamRankCard.tsx
Labels: ✨ Feature, 👾 본승

#62 Feat/#58 icon button, action button 컴포넌트
  src/app/(main-contents)/rank/teams/TeamRankContent.tsx
  src/components/common/button/ActionButton.tsx
  src/components/common/button/IconButton.tsx
  src/components/mypage/habits/HabitContent.tsx
  src/components/mypage/habits/HabitForm.tsx
  src/components/mypage/habits/HabitItem.tsx
  src/constants/mode.constants.ts
Labels: ✨ Feature, 🎨 Html&css, 🌱 수진

#63 Feat/#61-팀 해체/탈퇴 로직 구현
  package.json
  pnpm-lock.yaml
  src/app/(main-contents)/team/[id]/page.tsx
  src/app/(main-contents)/team/page.tsx
  src/components/common/ConfirmDialog.tsx
  src/components/team/TeamLeave.tsx
  src/components/team/team-delete/TeamDisbandButton.tsx
  src/components/team/team-delete/TeamLeaveButton.tsx
  src/components/ui/alert-dialog.tsx
  src/constants/path.constants.ts
  src/lib/services/team-actions.services.ts
  src/lib/services/team-client.services.ts
Labels: ✨ Feature, 🐻 민경, 📬 API

#67 Feat/#64-팀 가입 로직 구현
  prisma/schema.prisma
  src/app/(main-contents)/rank/teams/TeamRankContent.tsx
  src/app/api/teams/member/[id]/route.ts
  src/app/api/teams/member/route.ts
  src/components/rank/TeamRankCard.tsx
  src/components/team/TeamForm.tsx
  src/components/team/TeamJoin.tsx
  src/components/team/team-delete/TeamDisbandButton.tsx
  src/components/team/team-delete/TeamLeaveButton.tsx
  src/components/team/team-join/TeamJoinPrivateModal.tsx
  src/components/team/team-join/TeamPasswordForm.tsx
  src/constants/error-messages.constants.ts
  src/constants/placeholder.constants.ts
  src/lib/services/team-client.services.ts
  src/lib/utils/team-validation.utils.ts
Labels: ✨ Feature, 🐻 민경, 📬 API

#68 Feat/#65-team-websoket
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  prisma/schema.prisma
  src/app/(main-contents)/rank/teams/page.tsx
  src/app/(main-contents)/rank/users/page.tsx
  src/app/(main-contents)/team/[id]/page.tsx
  src/app/api/chat/route.ts
  src/components/common/commonModal.tsx
  src/components/rank/team/TeamDetailModalContents.tsx
  src/components/rank/team/TeamRankCard.tsx
  src/components/rank/team/TeamRankContent.tsx
  src/components/rank/user/UserRankCard.tsx
  src/components/rank/user/UserRankContent.tsx
  src/components/team/TeamChat.tsx
  src/constants/modal.constants.ts
  src/lib/pusher.ts
Labels: ✨ Feature, 👾 본승, 📬 API

#71 Refactor/#66 mypage refactoring
  src/app/(main-contents)/mypage/page.tsx
  src/app/api/habits/[id]/route.ts
  src/app/api/habits/route.ts
  src/app/api/user-points/route.ts
  src/components/mypage/MyPageCalendar.tsx
  src/components/mypage/MyPageHabits.tsx
  src/components/mypage/MyPageTeam.tsx
  src/components/mypage/MyTeam.tsx
  src/components/mypage/habits/HabitContent.tsx
  src/components/mypage/habits/HabitForm.tsx
  src/components/mypage/habits/HabitItem.tsx
  src/components/mypage/habits/habit-form/HabitFormInput.tsx
  src/components/mypage/habits/habit-form/HabitFormRepeatDays.tsx
  src/components/mypage/habits/habit-form/HabitFormTags.tsx
  src/constants/habits.constants.ts
  src/constants/validation.constants.ts
  src/lib/hooks/useHabitFormHandler.ts
  src/lib/hooks/useHabitItemHandlers.ts
  src/lib/mutations/useAddPointMutation.ts
  src/lib/mutations/useHabitMutation.ts
  src/lib/schema/habit-form.schema.ts
  src/lib/schema/habit.schema.ts
  src/lib/services/habit-client.services.ts
  src/lib/services/user-points.services.ts
  src/lib/utils/habit-validation.utils.ts
  src/lib/utils/habit.utils.ts
  src/types/habits.type.ts
Labels: 🔨 Refactor, 🌱 수진

#75 Refactor/#69-팀 페이지 관련 로직/컴포넌트 리팩토링
  src/app/(main-contents)/team/[id]/page.tsx
  src/app/(main-contents)/team/page.tsx
  src/components/common/ConfirmDialog.tsx
  src/components/common/ErrorMessage.tsx
  src/components/mypage/habits/HabitForm.tsx
  src/components/rank/team/TeamRankContent.tsx
  src/components/team/TeamForm.tsx
  src/components/team/TeamInfo.tsx
  src/components/team/TeamJoin.tsx
  src/components/team/TeamLeave.tsx
  src/components/team/TeamMemberCard.tsx
  src/components/team/TeamProgress.tsx
  src/components/team/team-create/TeamEmblemSelector.tsx
  src/components/team/team-create/TeamInputs.tsx
  src/components/team/team-delete/TeamDisbandButton.tsx
  src/components/team/team-delete/TeamLeaveButton.tsx
  src/components/team/team-edit/TeamBioEditMode.tsx
  src/components/team/team-edit/TeamBioNotEditMode.tsx
  src/components/team/team-edit/TeamOpenNotEditMode.tsx
  src/components/team/team-edit/TeamOpenToggleButton.tsx
  src/components/team/team-join/TeamJoinPrivateModal.tsx
  src/components/team/team-join/TeamPasswordForm.tsx
  src/components/ui/alert-dialog.tsx
  src/constants/error-messages.constants.ts
  src/constants/toast-messages.contants.ts
  src/lib/seo/generateTeamMetadata.tsx
Labels: 🔨 Refactor, 🐻 민경

#76 Refator/#73-rank-page
  src/app/api/teams/route.ts
  src/components/rank/team/TeamDetailModalContents.tsx
  src/components/rank/team/TeamNormalRankCard.tsx
  src/components/rank/team/TeamRankCard.tsx
  src/components/rank/team/TeamRankContent.tsx
  src/components/rank/team/TeamTopRankCard.tsx
  src/components/rank/user/UserNormalRankCard.tsx
  src/components/rank/user/UserRankCard.tsx
  src/components/rank/user/UserTopRankCard.tsx
  src/lib/queries/useTeamQuery.ts
  src/lib/queries/useUserQuery.ts
  src/lib/services/team-actions.services.ts
  src/lib/services/team-client.services.ts
  src/lib/services/user-actions.services.ts
  src/lib/services/user-client.services.ts
  src/types/rank.type.ts
Labels: 🔨 Refactor, 👾 본승

#80 Bugfix/#79-prisma 구조 변경
  prisma/schema.prisma
  src/constants/habits.constants.ts
Labels: 🐞 BugFix, 🐻 민경, 🌱 수진, 📬 API

#82 Bugfix/#81 categories enum
  src/components/mypage/habits/habit-form/HabitFormTags.tsx
  src/constants/habits.constants.ts
  src/lib/schema/habit.schema.ts
  src/lib/utils/habit.utils.ts
  src/types/habits.type.ts
Labels: 🐞 BugFix, 🌱 수진

#83 Refactor/#74-레이아웃 (네비바) 리팩토링
  src/app/(main-contents)/layout.tsx
  src/app/layout.tsx
  src/components/layout/LayoutWrapper.tsx
  src/components/layout/MainLayout.tsx
  src/components/layout/NavButton.tsx
  src/components/layout/Sidebar.tsx
  src/components/login/LogoutButton.tsx
  src/lib/services/user-actions.services.ts
  src/types/profile.type.ts
Labels: 🔨 Refactor, 🎨 Html&css, ♣ 한솔

#84 Refactor/#77-zod 추가, public assets 구조화 및 tailwind css 설정
  public/assets/fonts/BMDOHYEON.ttf
  public/assets/fonts/PretendardVariable.woff2
  public/assets/images/emblem-cat.png
  public/assets/images/emblem-deer.png
  public/assets/images/emblem-lion.png
  public/assets/images/emblem-owl.png
  public/assets/images/logo_test.png
  public/assets/images/test01.png
  public/assets/images/user_lv1.png
  public/assets/images/user_lv2.png
  public/assets/images/user_lv3.png
  public/assets/images/user_lv4.png
  public/assets/images/user_lv5.png
  src/app/(main-contents)/team/[id]/page.tsx
  src/app/(main-contents)/team/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/login/GoogleLogin.tsx
  src/components/mypage/MyPageProfile.tsx
  src/components/mypage/MyTeam.tsx
  src/components/mypage/NoTeam.tsx
  src/components/mypage/profile/UserProfileEdit.tsx
  src/components/team/TeamForm.tsx
  src/components/team/TeamImage.tsx
  src/components/team/TeamJoin.tsx
  src/components/team/TeamTitle.tsx
  src/components/team/team-delete/TeamDisbandButton.tsx
  src/components/team/team-delete/TeamLeaveButton.tsx
  src/components/team/team-edit/TeamBioEditMode.tsx
  src/components/team/team-edit/TeamOpenToggleButton.tsx
  src/components/team/team-join/TeamPasswordForm.tsx
  src/components/ui/toaster.tsx
  src/constants/magic-numbers.constants.ts
  src/lib/hooks/use-toast.ts
  src/lib/hooks/useHabitFormHandler.ts
  src/lib/hooks/useHabitItemHandlers.ts
  src/lib/hooks/useTeamCreateForm.ts
  src/lib/mutations/useTeamBioMutation.ts
  src/lib/mutations/useUserProfileMutation.ts
  src/lib/providers/Provider.tsx
  src/lib/schema/team.schema.ts
  src/lib/seo/generateTeamMetadata.tsx
  src/lib/services/team-client.services.ts
  src/lib/utils/team-validation.utils.ts
  tailwind.config.ts
Labels: ⚙ Setting, 🔨 Refactor, 🐻 민경

#87 Feat/#85-팀 페이지 1차 디자인 적용
  prisma/schema.prisma
  src/app/(main-contents)/layout.tsx
  src/app/(main-contents)/team/[id]/page.tsx
  src/components/common/ErrorMessage.tsx
  src/components/common/Title.tsx
  src/components/common/UserTitle.tsx
  src/components/common/button/LinkButton.tsx
  src/components/mypage/MyTeam.tsx
  src/components/team/TeamImage.tsx
  src/components/team/TeamInfo.tsx
  src/components/team/TeamMemberCard.tsx
  src/components/team/TeamMemberList.tsx
  src/components/team/TeamProgress.tsx
  src/components/team/TeamTitle.tsx
  src/components/team/team-edit/TeamBioEditMode.tsx
  src/components/team/team-edit/TeamOpenNotEditMode.tsx
  src/components/team/team-edit/TeamOpenToggleButton.tsx
  src/components/ui/progress.tsx
  src/components/ui/switch.tsx
  src/constants/mode.constants.ts
  src/lib/services/team-actions.services.ts
Labels: ✨ Feature, 🎨 Html&css, 🐻 민경

#89 Refactor/#78-팀 랭킹 페이지 리팩토링
  src/components/rank/RankLabel.tsx
  src/components/rank/team/TeamNormalRankCard.tsx
  src/components/rank/team/TeamOtherSection.tsx
  src/components/rank/team/TeamRankCard.tsx
  src/components/rank/team/TeamRankContent.tsx
  src/components/rank/team/TeamRankHeader.tsx
  src/components/rank/team/TeamTopRankCard.tsx
  src/components/rank/team/TeamTopSection.tsx
  src/components/rank/team/normal/NormalTeamEmblem.tsx
  src/components/rank/team/normal/NormalTeamInfo.tsx
  src/components/rank/team/normal/NormalTeamRankCard.tsx.tsx
  src/components/rank/team/normal/NormalTeamRankLabel.tsx
  src/components/rank/team/top/TopTeamEmblem.tsx
  src/components/rank/team/top/TopTeamInfo.tsx
  src/components/rank/team/top/TopTeamRankCard.tsx
  src/components/rank/team/top/TopTeamRankLabel.tsx
  src/components/rank/user/UserNormalRankCard.tsx
  src/components/rank/user/UserRankContent.tsx
  src/components/rank/user/UserTopRankCard.tsx
  src/lib/services/team-actions.services.ts
Labels: 🔨 Refactor, 👾 본승

#91 Feat/#72 dashboard UI
  src/app/(main-contents)/mypage/page.tsx
  src/app/api/user-points/route.ts
  src/components/common/CommonModal.tsx
  src/components/common/button/ActionButton.tsx
  src/components/common/button/IconButton.tsx
  src/components/mypage/MyPageCalendar.tsx
  src/components/mypage/MyPageHabits.tsx
  src/components/mypage/NoTeam.tsx
  src/components/mypage/habits/HabitContent.tsx
  src/components/mypage/habits/HabitForm.tsx
  src/components/mypage/habits/HabitHeader.tsx
  src/components/mypage/habits/HabitItem.tsx
  src/components/mypage/habits/HabitList.tsx
  src/components/mypage/habits/HabitsFilter.tsx
  src/components/mypage/habits/UserLevelProgress.tsx
  src/components/mypage/habits/habit-form/HabitFormInput.tsx
  src/components/mypage/habits/habit-form/HabitFormRepeatDays.tsx
  src/components/mypage/habits/habit-form/HabitFormTags.tsx
  src/constants/error-messages.constants.ts
  src/constants/mode.constants.ts
  src/lib/hooks/useHabitFormHandler.ts
  src/lib/mutations/useAddPointMutation.ts
  src/lib/mutations/useHabitMutation.ts
  src/lib/queries/useHabitsQuery.ts
  src/lib/seo/mypage.metadata.ts
  src/lib/services/getUserSession.services.ts
  src/lib/services/habit-actions.services.ts
  src/lib/services/habit-client.services.ts
  src/lib/services/user-points.services.ts
  src/lib/utils/habit.utils.ts
  src/types/habits.type.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Html&css, 🌱 수진, 📬 API

#95 Refactor/#88-fetch 및 session 로직 리팩토링, 팀 정보 수정 시 Optimistic Update 기능 삭제
  package.json
  prisma/schema.prisma
  src/_sample/app/api/sample/[id]/route.ts
  src/_sample/app/api/sample/route.ts
  src/_sample/app/clientPage.tsx
  src/_sample/app/layout.tsx
  src/_sample/app/serverPage.tsx
  src/_sample/components/SampleClientComponent.tsx
  src/_sample/constants/sample.ts
  src/_sample/lib/mutations/useSampleMutation.tsx
  src/_sample/lib/providers/sampleProvider.tsx
  src/_sample/lib/queries/useSampleQuery.tsx
  src/_sample/lib/server-actions/samle-server-action.ts
  src/_sample/lib/services/sampleServices.ts
  src/app/(main-contents)/layout.tsx
  src/app/(main-contents)/team/[id]/page.tsx
  src/app/api/chat/route.ts
  src/app/api/teams/member/route.ts
  src/app/api/teams/route.ts
  src/components/common/ConfirmDialog.tsx
  src/components/common/ErrorMessage.tsx
  src/components/mypage/MyPageTeam.tsx
  src/components/mypage/MyTeam.tsx
  src/components/team/TeamCalendar.tsx
  src/components/team/TeamInfo.tsx
  src/components/team/TeamJoin.tsx
  src/components/team/TeamLeave.tsx
  src/components/team/TeamMemberList.tsx
  src/components/team/team-edit/TeamBioEditMode.tsx
  src/constants/modal.constants.ts
  src/constants/mode.constants.ts
  src/constants/team-contents.constants.ts
  src/constants/teams.constants.ts
  src/lib/hooks/.gitkeep
  src/lib/hooks/useTeamBioUpdateForm.ts
  src/lib/hooks/useTeamCreateContents.ts
  src/lib/mutations/.gitkeep
  src/lib/mutations/useTeamBioMutation.ts
  src/lib/mutations/useTeamOpenMutation.ts
  src/lib/providers/.gitkeep
  src/lib/queries/.gitkeep
  src/lib/queries/useTeamQuery.ts
  src/lib/schema/team.schema.ts
  src/lib/seo/generateTeamMetadata.tsx
  src/lib/services/.gitkeep
  src/lib/services/team-actions.services.ts
  src/lib/services/team-client.services.ts
  src/lib/utils/team.utils.ts
  tailwind.config.ts
Labels: 🔨 Refactor, 🐻 민경

#97 Feat/#96-팀 가입 로직 TeamCard에 적용
  src/components/rank/team/TeamRankCard.tsx
  src/components/rank/team/normal/NormalTeamRankCard.tsx.tsx
  src/components/rank/team/top/TopTeamRankCard.tsx
  src/components/team/TeamJoin.tsx
  src/components/team/team-join/TeamJoinPrivateModal.tsx
  src/types/rank.type.ts
Labels: ✨ Feature, 🎨 Html&css, 🐻 민경

#98 Feat/#92 habits filter
  src/app/(main-contents)/mypage/page.tsx
  src/app/api/user-points/route.ts
  src/components/mypage/MyPageHabits.tsx
  src/components/mypage/MyPageProfile.tsx
  src/components/mypage/MyPageSection.tsx
  src/components/mypage/habits/HabitForm.tsx
  src/components/mypage/habits/HabitHeader.tsx
  src/components/mypage/habits/HabitItem.tsx
  src/components/mypage/habits/HabitList.tsx
  src/components/mypage/habits/HabitsFilter.tsx
  src/components/mypage/habits/UserLevelProgress.tsx
  src/components/mypage/habits/habit-filter/CetegoryFilter.tsx
  src/components/mypage/habits/habit-filter/DayFilter.tsx
  src/components/mypage/habits/habit-filter/HabitSelectButton.tsx
  src/components/mypage/habits/habit-form/HabitFormActions.tsx
  src/components/mypage/habits/habit-form/HabitFormFields.tsx
  src/components/mypage/habits/habit-form/HabitFormRepeatDays.tsx
  src/components/mypage/habits/habit-form/HabitFormTags.tsx
  src/components/mypage/habits/habit-item/HabitItemActions.tsx
  src/components/mypage/habits/habit-item/HabitItemInfo.tsx
  src/constants/mode.constants.ts
  src/constants/query-keys.constants.ts
  src/constants/time.constants.ts
  src/lib/hooks/useHabitsFilter.ts
  src/lib/mutations/useAddPointMutation.ts
  src/lib/mutations/useOptimisticMutation.ts
  src/lib/providers/TQProvider.tsx
  src/lib/queries/useHabitsQuery.ts
  src/lib/queries/useUserPointsQuery.ts
  src/lib/seo/mypage.metadata.ts
  src/lib/services/habit-actions.services.ts
  src/lib/services/user-points.services.ts
  src/lib/utils/auth-route-handler.utils.ts
  src/lib/utils/habit.utils.ts
Labels: ✨ Feature, 🔨 Refactor, 🌱 수진

#99 Refactor/#86-유저 프로필 정보 네비바로 이동
  public/assets/images/buttons/SealQuestion.png
  src/components/common/button/ActionButton.tsx
  src/components/layout/HowToUseButton.tsx
  src/components/layout/Sidebar.tsx
  src/components/layout/SidebarLogo.tsx
  src/components/layout/SidebarNav.tsx
  src/components/layout/SidebarProfile.tsx
  src/components/login/LogoutButton.tsx
  src/components/mypage/profile/UserProfileEdit.tsx
  src/constants/profile.constants.ts
  src/lib/utils/user.utils.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Html&css, ♣ 한솔

#107 Feat/#102-로딩/에러페이지 구현
  public/assets/images/logo_desktop_kkuitddo.png
  public/assets/images/logo_mobile_kkuitddo.png
  src/app/(main-contents)/mypage/page.tsx
  src/app/error.tsx
  src/app/fonts/GeistMonoVF.woff
  src/app/fonts/GeistVF.woff
  src/app/layout.tsx
  src/app/not-found.tsx
  src/components/loading-error-page/ErrorPageText.tsx
  src/components/loading-error-page/GlobalLoadingBar.tsx
  src/components/loading-error-page/UnauthorizedPage.tsx
  src/components/login/LogoutButton.tsx
  src/components/rank/team/TeamRankCard.tsx
  src/components/team/TeamInfo.tsx
  src/components/team/TeamLeave.tsx
  src/constants/.gitkeep
  src/constants/assets.contants.ts
  src/constants/team-contents.constants.ts
  tailwind.config.ts
Labels: ✨ Feature, 🐻 민경

#109 Style/#106 action button
  src/app/api/user-points/route.ts
  src/components/common/button/ActionButton.tsx
  src/components/common/button/IconButton.tsx
  src/components/mypage/habits/habit-filter/DayFilter.tsx
  src/components/mypage/habits/habit-filter/HabitSelectButton.tsx
  src/components/rank/SearchInput.tsx
  src/constants/mode.constants.ts
Labels: 🎨 Html&css, 🌱 수진

#115 Feat/#101 user points
  src/app/api/user-points/route.ts
  src/components/common/button/ActionButton.tsx
  src/components/mypage/MyPageHabits.tsx
  src/components/mypage/MyPageProfile.tsx
  src/components/mypage/habits/HabitItem.tsx
  src/components/mypage/habits/HabitList.tsx
  src/components/mypage/habits/habit-form/HabitFormActions.tsx
  src/components/mypage/habits/habit-form/HabitFormFields.tsx
  src/constants/error-messages.constants.ts
  src/constants/habits.constants.ts
  src/constants/mode.constants.ts
  src/lib/hooks/useHabitFormHandler.ts
  src/lib/hooks/useHabitItemHandlers.ts
  src/lib/hooks/useHabitRecords.ts
  src/lib/hooks/useHabitsControls.ts
  src/lib/hooks/useHabitsFilter.ts
  src/lib/mutations/useAddPointMutation.ts
  src/lib/services/revalidate-mypage.services.ts
  src/lib/services/user-points.services.ts
  src/lib/utils/habit-date.utils.ts
  src/lib/utils/habit-filter.utils.ts
  src/lib/utils/habit-form.utils.ts
  src/lib/utils/habit-points.utils.ts
  src/lib/utils/habit-validation.utils.ts
  src/lib/utils/habit.utils.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Html&css, 🌱 수진

#118 Refactor/#103-Home Page 스타일링 및 페이지 소개 추가
  public/assets/images/logo_test.png
  src/app/page.tsx
  src/components/common/UserTitle.tsx
  src/components/home/HomeBioContent.tsx
  src/components/home/HomePageItems.tsx
  src/components/home/HomePagination.tsx
  src/components/home/HomePaginationController.tsx
  src/components/home/contents/HomeBioPage1.tsx
  src/components/home/contents/HomeBioPage2.tsx
  src/components/home/contents/HomeBioPage3.tsx
  src/components/home/contents/items/BioPageItem.tsx
  src/components/layout/HowToUseButton.tsx
  src/components/layout/Sidebar.tsx
  src/components/layout/SidebarLogo.tsx
  src/components/layout/SidebarNav.tsx
  src/components/layout/SidebarProfile.tsx
  src/components/login/GoogleLogin.tsx
  src/components/login/LoginButton.tsx
  src/components/login/ToDashboardButton.tsx
  src/components/ui/pagination.tsx
  src/constants/toast-messages.contants.ts
  tailwind.config.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Html&css, ♣ 한솔

#119 Style/#116 mypage UI
  src/app/(main-contents)/mypage/page.tsx
  src/components/common/button/ActionButton.tsx
  src/components/common/button/IconButton.tsx
  src/components/mypage/MyPageHabits.tsx
  src/components/mypage/MyTeam.tsx
  src/components/mypage/habits/HabitForm.tsx
  src/components/mypage/habits/HabitHeader.tsx
  src/components/mypage/habits/HabitItem.tsx
  src/components/mypage/habits/HabitList.tsx
  src/components/mypage/habits/HabitsFilter.tsx
  src/components/mypage/habits/UserLevelProgress.tsx
  src/components/mypage/habits/habit-filter/CetegoryFilter.tsx
  src/components/mypage/habits/habit-filter/DayFilter.tsx
  src/components/mypage/habits/habit-filter/HabitSelectButton.tsx
  src/components/mypage/habits/habit-form/HabitFormActions.tsx
  src/components/mypage/habits/habit-form/HabitFormFields.tsx
  src/components/mypage/habits/habit-form/HabitFormInput.tsx
  src/components/mypage/habits/habit-form/HabitFormRepeatDays.tsx
  src/components/mypage/habits/habit-form/HabitFormTags.tsx
  src/components/mypage/habits/habit-item/HabitItemActions.tsx
  src/constants/habits.constants.ts
  src/constants/mode.constants.ts
  src/constants/toast-messages.contants.ts
  src/lib/hooks/useHabitFormHandler.ts
  src/lib/hooks/useHabitItemHandlers.ts
  src/lib/hooks/useHabitsFilter.ts
  src/lib/utils/habit-date.utils.ts
  src/lib/utils/habit-filter.utils.ts
  src/lib/utils/habit-form.utils.ts
Labels: ✨ Feature, 🎨 Html&css, 🌱 수진

#121 Style/#111-랭킹 페이지 디자인 구현
  src/components/mypage/habits/UserLevelProgress.tsx
  src/components/rank/RankLabel.tsx
  src/components/rank/SearchInput.tsx
  src/components/rank/team/TeamRankContent.tsx
  src/components/rank/team/TeamTopSection.tsx
  src/components/rank/team/normal/NormalTeamEmblem.tsx
  src/components/rank/team/normal/NormalTeamInfo.tsx
  src/components/rank/team/normal/NormalTeamRankCard.tsx.tsx
  src/components/rank/team/normal/NormalTeamRankLabel.tsx
  src/components/rank/team/top/TopTeamEmblem.tsx
  src/components/rank/team/top/TopTeamRankCard.tsx
  src/components/rank/user/UserDetailModal.tsx
  src/components/rank/user/UserRankContent.tsx
  src/components/rank/user/UserTopSection.tsx
  src/components/rank/user/nomal/NormalUserAvatar.tsx
  src/components/rank/user/nomal/NormalUserInfo.tsx
  src/components/rank/user/nomal/NormalUserRankCard.tsx
  src/components/rank/user/nomal/NormalUserRankLabel.tsx
  src/components/rank/user/top/TopUserAvatar.tsx
  src/components/rank/user/top/TopUserRankCard.tsx
  src/components/team/TeamChat.tsx
  src/lib/services/user-actions.services.ts
  src/types/rank.type.ts
Labels: 🎨 Html&css, 👾 본승

#126 Bugfix/#125 private join error
  src/components/common/ConfirmDialog.tsx
  src/components/rank/team/top/TopTeamRankCard.tsx
  src/components/team/team-join/TeamJoinPrivateModal.tsx
Labels: 🐞 BugFix, 🌱 수진

#129 Feat/#127 habits feedback
  src/components/common/ConfirmDialog.tsx
  src/components/common/button/IconButton.tsx
  src/components/mypage/habits/habit-filter/HabitSelectButton.tsx
  src/components/mypage/habits/habit-form/HabitFormFields.tsx
  src/components/mypage/habits/habit-form/HabitFormRepeatDays.tsx
  src/components/mypage/habits/habit-item/HabitItemActions.tsx
  src/constants/dialog.constants.ts
  src/constants/error-messages.constants.ts
  src/lib/schema/habit.schema.ts
Labels: ✨ Feature, 🌱 수진

#131 Feat/#130 team feedback
  src/components/common/ConfirmDialog.tsx
  src/components/common/button/ActionButton.tsx
  src/components/mypage/habits/HabitItem.tsx
  src/components/mypage/habits/habit-item/HabitItemActions.tsx
  src/components/team/TeamJoin.tsx
  src/components/team/TeamLeave.tsx
  src/components/team/TeamMemberCard.tsx
  src/components/team/team-delete/TeamDisbandButton.tsx
  src/components/team/team-delete/TeamLeaveButton.tsx
  src/components/ui/alert-dialog.tsx
  src/lib/seo/generateTeamMetadata.tsx
  src/lib/services/team-actions.services.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css, 🌱 수진

#132 Style/#124-애니메이션 적용
  package.json
  pnpm-lock.yaml
  src/components/home/HomeBioContent.tsx
  src/components/home/contents/items/BioPageItem.tsx
  src/components/mypage/habits/HabitForm.tsx
  src/components/rank/team/TeamRankCard.tsx
  src/components/rank/team/TeamTopSection.tsx
  src/components/rank/team/top/TopTeamInfo.tsx
  src/components/rank/team/top/TopTeamRankCard.tsx
  src/components/rank/team/top/TopTeamRankLabel.tsx
  src/components/rank/user/UserRankCard.tsx
  src/components/rank/user/UserTopSection.tsx
  src/components/rank/user/nomal/NormalUserRankCard.tsx
  src/components/rank/user/top/TopUserAvatar.tsx
  src/components/rank/user/top/TopUserRankCard.tsx
  src/components/team/TeamChat.tsx
  src/components/ui/alert-dialog.tsx
  src/lib/queries/useTeamQuery.ts
  src/lib/queries/useUserQuery.ts
  src/styles/rankCardStyles.ts
  src/types/rank.type.ts
  tailwind.config.ts
Labels: 🎨 Html&css, 👾 본승

#135 Refactor/#120-Edit Profile Refactoring
  src/components/common/button/IconButton.tsx
  src/components/layout/SidebarProfile.tsx
  src/components/layout/profile/UserLevel.tsx
  src/components/layout/profile/UserProfileEdit.tsx
  src/components/layout/profile/UserProfileEditMode.tsx
  src/components/layout/profile/UserProfileNotEditMode.tsx
  src/components/layout/profile/items/BioInputBar.tsx
  src/components/layout/profile/items/EditProfileButton.tsx
  src/components/login/GoogleLogin.tsx
  src/components/login/LoginButton.tsx
  src/components/mypage/habits/UserLevelProgress.tsx
  src/components/mypage/profile/UserProfileEdit.tsx
  src/components/mypage/profile/UserProgress.tsx
  src/constants/mode.constants.ts
  src/constants/toast-messages.contants.ts
  src/constants/validation.constants.ts
  src/lib/utils/user-validation.utils.ts
Labels: 🔨 Refactor, 🎨 Html&css, ♣ 한솔

#137 Feat/#133 mypage mobile
  src/app/(main-contents)/dashboard/page.tsx
  src/app/(main-contents)/layout.tsx
  src/app/(main-contents)/team/page.tsx
  src/app/error.tsx
  src/app/not-found.tsx
  src/components/dashboard/DashboardHabits.tsx
  src/components/dashboard/DashboardSection.tsx
  src/components/dashboard/DashboardTeam.tsx
  src/components/dashboard/MyTeam.tsx
  src/components/dashboard/NoTeam.tsx
  src/components/dashboard/habits/HabitForm.tsx
  src/components/dashboard/habits/HabitHeader.tsx
  src/components/dashboard/habits/HabitItem.tsx
  src/components/dashboard/habits/HabitList.tsx
  src/components/dashboard/habits/HabitsFilter.tsx
  src/components/dashboard/habits/UserLevelProgress.tsx
  src/components/dashboard/habits/habit-filter/CetegoryFilter.tsx
  src/components/dashboard/habits/habit-filter/DayFilter.tsx
  src/components/dashboard/habits/habit-filter/HabitSelectButton.tsx
  src/components/dashboard/habits/habit-filter/MobileCategoryFilter.tsx
  src/components/dashboard/habits/habit-form/HabitFormActions.tsx
  src/components/dashboard/habits/habit-form/HabitFormFields.tsx
  src/components/dashboard/habits/habit-form/HabitFormInput.tsx
  src/components/dashboard/habits/habit-form/HabitFormRepeatDays.tsx
  src/components/dashboard/habits/habit-form/HabitFormTags.tsx
  src/components/dashboard/habits/habit-item/HabitItemActions.tsx
  src/components/dashboard/habits/habit-item/HabitItemInfo.tsx
  src/components/dashboard/profile/UserLevel.tsx
  src/components/dashboard/profile/UserProfileEdit.tsx
  src/components/dashboard/profile/UserProgress.tsx
  src/components/layout/SidebarNav.tsx
  src/components/loading-error-page/GlobalLoadingBar.tsx
  src/components/login/LogoutButton.tsx
  src/components/login/ToDashboardButton.tsx
  src/components/mypage/MyPageSection.tsx
  src/components/mypage/MyTeam.tsx
  src/components/rank/user/UserDetailModal.tsx
  src/components/team/TeamJoin.tsx
  src/components/team/TeamProgress.tsx
  src/components/team/team-delete/TeamDisbandButton.tsx
  src/components/team/team-delete/TeamLeaveButton.tsx
  src/components/team/team-join/TeamPasswordForm.tsx
  src/constants/path.constants.ts
  src/constants/toast-messages.contants.ts
  src/lib/hooks/useMediaQuery.ts
  src/lib/mutations/useAddPointMutation.ts
  src/lib/seo/dashboard.metadata.ts
  src/lib/services/revalidate-dashboard.services.ts
  src/lib/utils/auth.ts
Labels: 🔨 Refactor, 🎨 Html&css, 🌱 수진

#139 Feat/#138 sidebar mobile
  src/app/(main-contents)/layout.tsx
  src/app/page.tsx
  src/components/common/button/LinkButton.tsx
  src/components/dashboard/habits/HabitsFilter.tsx
  src/components/home/HomePageItems.tsx
  src/components/home/HomePagination.tsx
  src/components/home/HomePaginationController.tsx
  src/components/home/contents/HomeBioPage1.tsx
  src/components/home/contents/HomeBioPage3.tsx
  src/components/home/contents/items/BioPageItem.tsx
  src/components/layout/MobileHeader.tsx
  src/components/layout/Sidebar.tsx
  src/components/layout/SidebarLogo.tsx
  src/components/layout/SidebarMobileWrapper.tsx
  src/components/layout/SidebarNav.tsx
  src/components/layout/SidebarProfile.tsx
  src/components/layout/SlideSidebar.tsx
  src/lib/hooks/useMediaQuery.ts
  src/lib/queries/useMyTeamQuery.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Html&css, 🌱 수진

#140 Refactor/#134 rank page refactor
  src/components/common/CommonModal.tsx
  src/components/common/UserTitle.tsx
  src/components/common/button/MobileTabButton.tsx
  src/components/rank/RankLabel.tsx
  src/components/rank/team/TeamOtherSection.tsx
  src/components/rank/team/TeamRankContent.tsx
  src/components/rank/team/TeamRankHeader.tsx
  src/components/rank/team/TeamTopSection.tsx
  src/components/rank/team/normal/NormalTeamEmblem.tsx
  src/components/rank/team/normal/NormalTeamInfo.tsx
  src/components/rank/team/normal/NormalTeamRankCard.tsx.tsx
  src/components/rank/team/top/TopTeamEmblem.tsx
  src/components/rank/team/top/TopTeamRankCard.tsx
  src/components/rank/user/UserOtherSection.tsx
  src/components/rank/user/UserRankContent.tsx
  src/components/rank/user/UserRankHeader.tsx
  src/components/rank/user/UserTopSection.tsx
  src/components/rank/user/nomal/NormalUserAvatar.tsx
  src/components/rank/user/nomal/NormalUserInfo.tsx
  src/components/rank/user/top/TopUserAvatar.tsx
  src/components/rank/user/top/TopUserRankCard.tsx
  src/lib/services/search-actions.services.ts
  src/lib/services/team-actions.services.ts
  src/lib/services/user-actions.services.ts
  src/types/rank.type.ts
Labels: 🔨 Refactor, 🎨 Html&css, 👾 본승

#145 Feat/#128-토스페이먼츠 결제 위젯 및 API 연동
  package.json
  pnpm-lock.yaml
  prisma/schema.prisma
  src/app/(main-contents)/shop/payments/fail/page.tsx
  src/app/(main-contents)/shop/payments/success/page.tsx
  src/app/api/payments/fail/route.ts
  src/app/api/payments/route.ts
  src/app/api/payments/success/route.ts
  src/components/shop/PurchaseButton.tsx
  src/components/shop/TossPaymentModal.tsx
  src/constants/error-messages.constants.ts
  src/constants/path.constants.ts
  src/lib/hooks/useTossWidget.ts
  src/lib/services/payment-client.services.ts
  src/lib/services/toss-api.services.ts
Labels: ✨ Feature, 🐻 민경, 📬 API

#147 Feat/#143 dashboard sidebar mobile
  src/app/(main-contents)/team/page.tsx
  src/components/dashboard/MyTeam.tsx
  src/components/dashboard/NoTeam.tsx
  src/components/dashboard/habits/HabitForm.tsx
  src/components/dashboard/habits/HabitList.tsx
  src/components/dashboard/habits/UserLevelProgress.tsx
  src/components/dashboard/habits/habit-filter/MobileCategoryFilter.tsx
  src/components/dashboard/habits/habit-form/HabitFormTags.tsx
  src/components/layout/MobileHeader.tsx
  src/components/layout/Sidebar.tsx
  src/components/layout/SidebarMobileWrapper.tsx
  src/components/layout/SidebarNav.tsx
  src/components/layout/SlideSidebar.tsx
  src/components/team/TeamInfo.tsx
  src/components/team/team-edit/TeamBioEditMode.tsx
  src/components/ui/select.tsx
Labels: ✨ Feature, 🎨 Html&css, 🌱 수진

#148 Style/#144 team page style
  src/app/(main-contents)/team/[id]/page.tsx
  src/components/common/ConfirmDialog.tsx
  src/components/common/button/MobileTabButton.tsx
  src/components/rank/team/TeamRankHeader.tsx
  src/components/rank/team/top/TopTeamRankCard.tsx
  src/components/rank/user/UserRankHeader.tsx
  src/components/team/TeamChat.tsx
  src/components/team/TeamTab.tsx
  src/components/ui/progress.tsx
  src/styles/tabButtonStyles.ts
Labels: 🎨 Html&css, 👾 본승

#150 Deploy/#149-UT 전 마지막 Merge
  package.json
  pnpm-lock.yaml
  prisma/schema.prisma
  src/app/(main-contents)/shop/payments/fail/page.tsx
  src/app/(main-contents)/shop/payments/success/page.tsx
  src/app/(main-contents)/team/[id]/page.tsx
  src/app/(main-contents)/team/page.tsx
  src/app/api/payments/fail/route.ts
  src/app/api/payments/route.ts
  src/app/api/payments/success/route.ts
  src/components/common/ConfirmDialog.tsx
  src/components/common/button/MobileTabButton.tsx
  src/components/dashboard/MyTeam.tsx
  src/components/dashboard/NoTeam.tsx
  src/components/dashboard/habits/HabitForm.tsx
  src/components/dashboard/habits/HabitList.tsx
  src/components/dashboard/habits/UserLevelProgress.tsx
  src/components/dashboard/habits/habit-filter/MobileCategoryFilter.tsx
  src/components/dashboard/habits/habit-form/HabitFormTags.tsx
  src/components/layout/MobileHeader.tsx
  src/components/layout/Sidebar.tsx
  src/components/layout/SidebarMobileWrapper.tsx
  src/components/layout/SidebarNav.tsx
  src/components/layout/SlideSidebar.tsx
  src/components/rank/team/TeamRankHeader.tsx
  src/components/rank/team/top/TopTeamRankCard.tsx
  src/components/rank/user/UserRankHeader.tsx
  src/components/shop/PurchaseButton.tsx
  src/components/shop/TossPaymentModal.tsx
  src/components/team/TeamChat.tsx
  src/components/team/TeamInfo.tsx
  src/components/team/TeamTab.tsx
  src/components/team/team-edit/TeamBioEditMode.tsx
  src/components/ui/progress.tsx
  src/components/ui/select.tsx
  src/constants/error-messages.constants.ts
  src/constants/path.constants.ts
  src/lib/hooks/useTossWidget.ts
  src/lib/services/payment-client.services.ts
  src/lib/services/toss-api.services.ts
  src/styles/tabButtonStyles.ts
Labels: ♣ 한솔, 🌏 Deploy

#151 Style/#144-모바일 팀 리스트 ui 변경
  src/components/team/TeamMemberCard.tsx
  src/constants/team-contents.constants.ts
Labels: 🎨 Html&css, 👾 본승

#152 Deploy/#149-UT 전 진짜 마지막 Merge
  src/components/layout/Sidebar.tsx
  src/components/layout/SidebarNav.tsx
  src/components/team/TeamMemberCard.tsx
  src/constants/team-contents.constants.ts
Labels: ♣ 한솔, 🌏 Deploy

#155 Feat/#146-아이템 관련 DB 세팅 및 구매 로직 구현
  prisma/schema.prisma
  public/assets/images/fail_big.png
  public/assets/images/items/bronze-diamond.png
  public/assets/images/items/bronze-star.png
  public/assets/images/items/diamond-wing.png
  public/assets/images/items/gold-diamond.png
  public/assets/images/items/gold-star.png
  public/assets/images/items/ruby-wing.png
  public/assets/images/items/silver-diamond.png
  public/assets/images/items/silver-star.png
  public/assets/images/items/star-wing.png
  public/assets/images/kkuitddo-favicon.ico
  public/assets/images/success_big.png
  src/app/(main-contents)/shop/page.tsx
  src/app/(main-contents)/shop/payments/fail/page.tsx
  src/app/(main-contents)/shop/payments/success/page.tsx
  src/app/(main-contents)/team/page.tsx
  src/app/api/payments/success/route.ts
  src/app/favicon.ico
  src/app/layout.tsx
  src/components/common/Title.tsx
  src/components/common/button/ActionButton.tsx
  src/components/common/button/IconButton.tsx
  src/components/common/button/LinkButton.tsx
  src/components/dashboard/habits/HabitEmptyState.tsx
  src/components/dashboard/habits/HabitHeader.tsx
  src/components/dashboard/habits/HabitItem.tsx
  src/components/dashboard/habits/HabitList.tsx
  src/components/dashboard/habits/habit-filter/DayFilter.tsx
  src/components/dashboard/habits/habit-filter/MobileCategoryFilter.tsx
  src/components/dashboard/habits/habit-form/HabitFormFields.tsx
  src/components/dashboard/habits/habit-item/HabitDaysBadge.tsx
  src/components/layout/SidebarNav.tsx
  src/components/shop/NotPurchasedItemCard.tsx
  src/components/shop/NotPurchasedItemList.tsx
  src/components/shop/PurchaseButton.tsx
  src/components/shop/ShopItemList.tsx
  src/components/team/TeamJoin.tsx
  src/constants/assets.contants.ts
  src/constants/dialog.constants.ts
  src/constants/error-messages.constants.ts
  src/constants/habits.constants.ts
  src/constants/mode.constants.ts
  src/constants/placeholder.constants.ts
  src/constants/toast-messages.contants.ts
  src/lib/hooks/useHabitsFilter.ts
  src/lib/queries/useMyTeamQuery.ts
  src/lib/services/payment-actions.services.ts
  src/lib/services/team-actions.services.ts
  src/lib/services/toss-api.services.ts
  src/lib/utils/habit-form.utils.ts
  src/styles/paymentResultStyles.ts
  src/types/shop.type.ts
Labels: ✨ Feature, 🎨 Html&css, 🐻 민경, 📬 API

#157 Style/#155멤버리스트 반응형 UI 적용
  src/components/team/TeamMemberAvatar.tsx
  src/components/team/TeamMemberCard.tsx
Labels: 🎨 Html&css, 👾 본승

#160 Refactor/#158-shop 아이템 카드 style 리팩토링
  src/components/shop/NotPurchasedItemCard.tsx
  src/components/shop/NotPurchasedItemList.tsx
  src/components/shop/ShopItemList.tsx
  src/styles/shopItemListStyles.ts
Labels: 🔨 Refactor, 🎨 Html&css, 🐻 민경

#163 Feat/#161-프로필 UT 피드백 반영
  src/app/page.tsx
  src/components/home/HomePageItems.tsx
  src/components/home/HomePaginationController.tsx
  src/components/home/contents/items/BioPageItem.tsx
  src/components/layout/profile/UserProfileEditMode.tsx
  src/components/layout/profile/UserProfileNotEditMode.tsx
  src/components/login/LoginButton.tsx
  src/components/login/ToDashboardButton.tsx
  src/constants/error-messages.constants.ts
  src/constants/placeholder.constants.ts
  src/constants/validation.constants.ts
  src/lib/hooks/useUserUpdateForm.ts
  src/lib/schema/user.schema.ts
Labels: ✨ Feature, 🎨 Html&css, 🐻 민경

#164 Feat/#159-dashboard ut
  src/components/dashboard/DashboardHabits.tsx
  src/components/dashboard/MyTeam.tsx
  src/components/dashboard/habits/HabitItem.tsx
  src/components/dashboard/habits/HabitList.tsx
  src/components/dashboard/habits/UserLevelProgress.tsx
  src/components/dashboard/habits/habit-form/HabitFormInput.tsx
  src/components/dashboard/habits/habit-item/HabitCategoryBadge.tsx
  src/components/dashboard/habits/habit-item/HabitDaysBadge.tsx
  src/components/rank/user/UserDetailModal.tsx
  src/components/team/TeamInfo.tsx
  src/components/team/TeamProgress.tsx
  src/components/team/TeamTitle.tsx
  src/components/team/team-edit/TeamBioEditMode.tsx
  src/constants/error-messages.constants.ts
  src/constants/habits.constants.ts
  src/lib/hooks/useHabitItemState.ts
  src/lib/hooks/useHabitRecords.ts
  src/lib/utils/habit-date.utils.ts
  src/lib/utils/habit-filter.utils.ts
  src/lib/utils/habit-form.utils.ts
  src/lib/utils/habit-points.utils.ts
  src/lib/utils/habit.utils.ts
Labels: ✨ Feature, 🎨 Html&css, 🌱 수진

#167 Feat/#166-팀 UT 피드백 반영
  src/app/(main-contents)/layout.tsx
  src/components/common/ConfirmDialog.tsx
  src/components/common/button/ActionButton.tsx
  src/components/login/LoginButton.tsx
  src/components/login/ToDashboardButton.tsx
  src/components/team/TeamChat.tsx
  src/components/team/TeamJoin.tsx
  src/components/team/TeamMemberList.tsx
  src/components/team/TeamTab.tsx
  src/components/team/team-delete/TeamDisbandButton.tsx
  src/components/team/team-delete/TeamLeaveButton.tsx
  src/components/team/team-join/TeamInviteButton.tsx
  src/components/team/team-join/TeamInviteModal.tsx
  src/components/team/team-join/TeamJoinPrivateModal.tsx
  src/components/team/team-join/TeamLinkShareButton.tsx
  src/constants/mode.constants.ts
  src/constants/path.constants.ts
  src/constants/toast-messages.contants.ts
  src/lib/hooks/useKakaoShare.ts
  src/lib/seo/generateTeamMetadata.tsx
  src/lib/services/team-actions.services.ts
Labels: ✨ Feature, 🎨 Html&css, 🐻 민경

#171 Feat/#165-dashboard habit list 더보기
  src/app/(main-contents)/dashboard/page.tsx
  src/app/api/habits/route.ts
  src/app/api/payments/route.ts
  src/app/api/user-points/route.ts
  src/components/common/button/IconButton.tsx
  src/components/dashboard/DashboardHabits.tsx
  src/components/dashboard/habits/HabitHeader.tsx
  src/components/dashboard/habits/HabitList.tsx
  src/components/dashboard/habits/HabitsFilter.tsx
  src/components/dashboard/habits/habit-filter/DayFilter.tsx
  src/components/dashboard/habits/habit-filter/HabitSelectButton.tsx
  src/components/dashboard/habits/habit-filter/MobileCategoryFilter.tsx
  src/constants/habits.constants.ts
  src/constants/query-keys.constants.ts
  src/lib/hooks/useHabitRecords.ts
  src/lib/hooks/useHabitsControls.ts
  src/lib/hooks/useHabitsFilter.ts
  src/lib/mutations/useAddPointMutation.ts
  src/lib/mutations/useHabitMutation.ts
  src/lib/mutations/useOptimisticMutation.ts
  src/lib/queries/useHabitsQuery.ts
  src/lib/services/habit-actions.services.ts
  src/lib/services/habit-client.services.ts
  src/lib/services/team-actions.services.ts
  src/lib/utils/habit-date.utils.ts
  src/lib/utils/habit-filter.utils.ts
  src/lib/utils/habit-form.utils.ts
  src/lib/utils/habit-points.utils.ts
  src/lib/utils/habit.utils.ts
  src/lib/utils/user-level.utils.ts
  src/types/habits.type.ts
Labels: ✨ Feature, 🎨 Html&css, 🌱 수진, 📬 API

#174 Feat/#169-tooltip 구현
  package.json
  pnpm-lock.yaml
  src/components/common/CommonTooltip.tsx
  src/components/dashboard/habits/HabitItem.tsx
  src/components/dashboard/habits/HabitsFilter.tsx
  src/components/rank/team/top/TopTeamRankCard.tsx
  src/components/team/TeamLeave.tsx
  src/components/team/TeamMemberList.tsx
  src/components/team/team-join/TeamJoinPrivateModal.tsx
  src/components/ui/tooltip.tsx
  src/constants/tooltip-message.constants.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Html&css, 🐻 민경

#173 Feat/#162-랭킹 페이지 더보기 구현 및 UI수정
  src/app/api/rank/teams/route.ts
  src/app/api/rank/users/route.ts
  src/components/common/CommonLoadingSpinner.tsx
  src/components/layout/Sidebar.tsx
  src/components/layout/SidebarMobileWrapper.tsx
  src/components/rank/SearchInput.tsx
  src/components/rank/ShowMoreWrapper.tsx
  src/components/rank/team/ShowMoreWrapper.tsx
  src/components/rank/team/TeamOtherSection.tsx
  src/components/rank/team/TeamRankCard.tsx
  src/components/rank/team/TeamRankContent.tsx
  src/components/rank/team/TeamRankHeader.tsx
  src/components/rank/team/TeamTopSection.tsx
  src/components/rank/team/normal/NormalTeamInfo.tsx
  src/components/rank/team/normal/NormalTeamRankCard.tsx.tsx
  src/components/rank/team/top/TopTeamRankCard.tsx
  src/components/rank/user/UserOtherSection.tsx
  src/components/rank/user/UserRankContent.tsx
  src/components/rank/user/UserRankHeader.tsx
  src/components/rank/user/top/TopUserRankCard.tsx
  src/constants/path.constants.ts
  src/constants/placeholder.constants.ts
  src/constants/rank-pagination.constants.ts
  src/lib/queries/useTeamRankQuery.ts
  src/lib/queries/useUserRankQuery.ts
  src/lib/services/search-actions.services.ts
  src/lib/services/team-actions.services.ts
  src/lib/services/team-client.services.ts
  src/lib/services/user-actions.services.ts
  src/lib/services/user-client.services.ts
  src/types/rank.type.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Html&css, 👾 본승, 📬 API

#178 Feat/#175-랭킹 페이지 카드 기능 수정
  src/app/(main-contents)/team/[id]/page.tsx
  src/components/common/CommonTooltip.tsx
  src/components/common/ConfirmDialog.tsx
  src/components/dashboard/habits/HabitItem.tsx
  src/components/rank/team/TeamDetailModalContents.tsx
  src/components/rank/team/TeamRankCard.tsx
  src/components/rank/team/normal/NormalTeamRankCard.tsx.tsx
  src/components/rank/team/top/TopTeamRankCard.tsx
  src/components/rank/user/nomal/NormalUserRankCard.tsx
  src/components/rank/user/top/TopUserAvatar.tsx
  src/components/team/TeamChat.tsx
  src/components/team/TeamChatDisabled.tsx
  src/components/team/TeamMemberList.tsx
  src/components/team/team-delete/TeamDisbandButton.tsx
  src/components/team/team-delete/TeamLeaveButton.tsx
  src/components/team/team-join/TeamInviteButton.tsx
  src/constants/tooltip-message.constants.ts
Labels: ✨ Feature, 🎨 Html&css, 🐻 민경

#180 Feat/#172 dashboard point ut
  src/app/api/habits/route.ts
  src/app/api/user-points/route.ts
  src/components/common/CommonModal.tsx
  src/components/dashboard/DashboardHabits.tsx
  src/components/dashboard/habits/HabitHeader.tsx
  src/components/dashboard/habits/HabitItem.tsx
  src/components/dashboard/habits/HabitList.tsx
  src/components/dashboard/habits/HabitListLoading.tsx
  src/components/dashboard/habits/habit-filter/HabitSelectButton.tsx
  src/components/dashboard/habits/habit-form/HabitFormFields.tsx
  src/components/dashboard/habits/habit-form/HabitFormRepeatDays.tsx
  src/components/dashboard/habits/habit-item/HabitDaysBadge.tsx
  src/components/layout/SidebarMobileWrapper.tsx
  src/components/layout/SlideSidebar.tsx
  src/components/loading-error-page/GlobalLoadingBar.tsx
  src/components/loading-error-page/UnauthorizedPage.tsx
  src/components/rank/team/top/TopTeamRankCard.tsx
  src/components/rank/user/top/TopUserRankCard.tsx
  src/components/ui/alert-dialog.tsx
  src/components/ui/calendar.tsx
  src/components/ui/select.tsx
  src/components/ui/toast.tsx
  src/constants/breakpoints.constants.ts
  src/constants/habits.constants.ts
  src/constants/mode.constants.ts
  src/constants/z-index.constants.ts
  src/lib/hooks/useHabitRecords.ts
  src/lib/hooks/useHabitRepeatDays.ts
  src/lib/utils/habit-date.utils.ts
  src/lib/utils/habit-form.utils.ts
  src/lib/utils/habit-points.utils.ts
  src/lib/utils/habit.utils.ts
Labels: ✨ Feature, 🎨 Html&css, 🌱 수진

#182 Feat/#177-Shop 관련 컴포넌트에 Tanstack Query 추가, 프로필에 테두리 적용
  src/app/(main-contents)/shop/payments/fail/page.tsx
  src/app/(main-contents)/shop/payments/success/page.tsx
  src/app/api/items/not-purchased-items/route.ts
  src/app/api/items/purchased-items/route.ts
  src/app/api/items/route.ts
  src/app/api/user-items/[userItemId]/route.ts
  src/app/error.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/components/common/UserProfileImage.tsx
  src/components/common/button/ActionButton.tsx
  src/components/dashboard/NoTeam.tsx
  src/components/home/contents/HomeBioPage3.tsx
  src/components/home/contents/items/BioPageItem.tsx
  src/components/layout/MobileHeader.tsx
  src/components/layout/SidebarLogo.tsx
  src/components/layout/SidebarProfile.tsx
  src/components/loading-error-page/GlobalLoadingBar.tsx
  src/components/loading-error-page/UnauthorizedPage.tsx
  src/components/shop/NotPurchasedItemList.tsx
  src/components/shop/PurchasedItemList.tsx
  src/components/shop/ShopItemList.tsx
  src/components/team/team-join/TeamJoinPrivateModal.tsx
  src/constants/assets.constants.ts
  src/constants/error-messages.constants.ts
  src/constants/query-keys.constants.ts
  src/constants/team-contents.constants.ts
  src/lib/queries/usePurchasedItemsQuery.ts
  src/lib/services/payment-actions.services.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Html&css, ♣ 한솔

#181 Feat/#179-팀 페이지 로딩스피너 추가
  src/components/dashboard/MyTeam.tsx
  src/components/team/TeamInfo.tsx
  src/components/team/TeamTitle.tsx
  src/components/team/team-edit/TeamBioEditMode.tsx
  src/components/team/team-edit/TeamBioNotEditMode.tsx
  src/components/team/team-edit/TeamOpenNotEditMode.tsx
  src/components/team/team-edit/TeamOpenToggleButton.tsx
Labels: ✨ Feature, 🎨 Html&css, 🐻 민경

#192 Butfix/#190 ut feedback
  src/components/dashboard/DashboardTeam.tsx
  src/components/dashboard/MyTeam.tsx
  src/components/dashboard/habits/HabitItem.tsx
  src/components/rank/team/normal/NormalTeamInfo.tsx
  src/components/rank/team/top/TopTeamRankCard.tsx
  src/components/team/TeamInfo.tsx
  src/components/team/team-edit/TeamOpenNotEditMode.tsx
  src/components/team/team-edit/TeamOpenToggleButton.tsx
  src/components/team/team-join/TeamJoinPrivateModal.tsx
  src/components/team/team-join/TeamPasswordForm.tsx
  src/components/ui/switch.tsx
  src/lib/queries/useHabitsQuery.ts
Labels: 🐞 BugFix, 🎨 Html&css, 🌱 수진

#193 Hotfix/#191-토스트 누르면 닫히는 기능 추가, 사이드바 버튼 한글로 변경
  src/components/layout/profile/items/EditProfileButton.tsx
  src/components/login/LogoutButton.tsx
  src/components/ui/toaster.tsx
  src/lib/hooks/use-toast.ts
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor, ♣ 한솔

#194 Feat/#189 how to use modal fix
  public/assets/images/how-to-use-team.png
  src/app/globals.css
  src/components/common/CommonModal.tsx
  src/components/common/button/ActionButton.tsx
  src/components/layout/profile/HowToUse.tsx
  src/components/layout/profile/HowToUseModal.tsx
  src/components/rank/team/TeamRankHeader.tsx
  src/components/rank/team/normal/NormalTeamRankCard.tsx.tsx
  src/components/rank/user/UserDetailModal.tsx
  src/components/rank/user/UserRankHeader.tsx
  src/components/team/TeamChat.tsx
  src/components/team/TeamMemberAvatar.tsx
  src/components/team/TeamMemberCard.tsx
  src/components/team/TeamMemberList.tsx
Labels: 🎨 Html&css, 👾 본승

#196 Bugfix/#187-아이템 적용 오류 해결
  src/app/(main-contents)/shop/page.tsx
  src/app/api/user-items/[userItemId]/route.ts
  src/app/api/users/[id]/route.ts
  src/components/common/UserProfileImage.tsx
  src/components/common/button/ActionButton.tsx
  src/components/layout/SidebarProfile.tsx
  src/components/rank/user/UserRankContent.tsx
  src/components/rank/user/nomal/NormalUserRankCard.tsx
  src/components/rank/user/top/TopUserRankCard.tsx
  src/components/shop/PurchasedItemList.tsx
  src/components/shop/ShopItemList.tsx
  src/components/shop/items/AppliedButton.tsx
  src/components/shop/items/ApplyButton.tsx
  src/components/team/TeamMemberCard.tsx
  src/components/team/TeamMemberList.tsx
  src/constants/query-keys.constants.ts
  src/lib/queries/useUserQuery.ts
  src/lib/services/getUserClientSession.services.ts
  src/lib/services/payment-actions.services.ts
  src/lib/services/team-actions.services.ts
  src/lib/services/user-actions.services.ts
  src/lib/services/user-client.services.ts
  src/types/rank.type.ts
Labels: 🐞 BugFix, 🎨 Html&css, 🐻 민경

#201 Bugfix/#200-route 캐시 처리로 아이템 적용 문제 해결
  src/components/rank/team/TeamRankHeader.tsx
  src/components/rank/user/UserRankHeader.tsx
  src/components/shop/PurchasedItemList.tsx
Labels: 🐞 BugFix, 🐻 민경

#202 [Merge] Guest Login 구현이 완료된 Guest Branch를 Dev Branch 로 Merge
  prisma/schema.prisma
  src/components/login/LoginButton.tsx
  src/lib/utils/auth.ts
Labels: ✨ Feature, ♣ 한솔

#203 Deploy/#195-8차 Merge (Final Merge)
  prisma/schema.prisma
  src/components/layout/SidebarNav.tsx
  src/components/login/LoginButton.tsx
  src/components/rank/team/TeamRankHeader.tsx
  src/components/rank/user/UserRankHeader.tsx
  src/components/shop/PurchasedItemList.tsx
  src/lib/utils/auth.ts
Labels: ♣ 한솔, 🌏 Deploy

#205 Docs/#204-README 작성
  README.md
Labels: 📃 Docs, 🐻 민경

#210 Hotfix/#207 아바타 오류 수정
  README.md
  src/components/common/UserProfileImage.tsx
  src/components/dashboard/NoTeam.tsx
  src/components/layout/SidebarProfile.tsx
  src/components/loading-error-page/GlobalLoadingBar.tsx
  src/components/rank/user/nomal/NormalUserInfo.tsx
  src/components/rank/user/nomal/NormalUserRankCard.tsx
  src/components/rank/user/top/TopUserRankCard.tsx
  src/components/shop/NotPurchasedItemList.tsx
  src/components/shop/PurchasedItemList.tsx
  src/components/team/TeamMemberCard.tsx
Labels: 🐞 BugFix, 👾 본승

#209 Feat/#206-kkuittoo style
  README.md
  src/components/common/button/IconButton.tsx
  src/components/home/HomePaginationController.tsx
  src/components/home/contents/HomeBioPage1.tsx
  src/components/home/contents/items/BioPageItem.tsx
  src/components/layout/Sidebar.tsx
  src/components/layout/SidebarMobileWrapper.tsx
  src/components/layout/SidebarNav.tsx
  src/components/layout/profile/UserProfileEditMode.tsx
  src/components/layout/profile/UserProfileNotEditMode.tsx
  src/components/loading-error-page/GlobalLoadingBar.tsx
  src/components/team/TeamInfo.tsx
  src/components/team/TeamProgress.tsx
Labels: 🎨 Html&css, 🌱 수진

#212 Deploy/#211-dev->main 머지
  README.md
  src/components/common/UserProfileImage.tsx
  src/components/common/button/IconButton.tsx
  src/components/home/HomePaginationController.tsx
  src/components/home/contents/HomeBioPage1.tsx
  src/components/home/contents/items/BioPageItem.tsx
  src/components/layout/Sidebar.tsx
  src/components/layout/SidebarMobileWrapper.tsx
  src/components/layout/SidebarNav.tsx
  src/components/layout/SidebarProfile.tsx
  src/components/layout/profile/UserProfileEditMode.tsx
  src/components/layout/profile/UserProfileNotEditMode.tsx
  src/components/loading-error-page/GlobalLoadingBar.tsx
  src/components/rank/user/nomal/NormalUserRankCard.tsx
  src/components/rank/user/top/TopUserRankCard.tsx
  src/components/team/TeamInfo.tsx
  src/components/team/TeamMemberCard.tsx
  src/components/team/TeamProgress.tsx
  src/constants/image.constants.ts
Labels: 🌱 수진, 🌏 Deploy
